// services/mockData.ts — МОК-ДАННЫЕ ДЛЯ DEMO И INVESTOR PITCH 2025
// ФИНАЛЬНАЯ ВЕРСИЯ — ГОТОВА К DEMO И INVESTOR PITCH

import { Listing } from '@/types';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'Toyota Camry 2020 XLE',
    price: 2850000,
    currency: 'KGS',
    category: 'car',
    seller_id: 'seller-1',
    video_id: 'video-1',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1544636331-2c23e3c9b5f4?w=800&q=80',
    city: 'Бишкек',
    status: 'active',
    created_at: '2025-01-20T10:00:00Z',
    updated_at: '2025-01-20T10:00:00Z',
    views: 1234,
    likes: 89,
    saves: 23,
    shares: 12,
    messages_count: 5,
    comments_count: 15,
    views_count: 1234,
    likes_count: 89,
    ai_score: 94,
    is_promoted: true,
    boost_expires_at: '2025-01-25T23:59:59Z',
    boost_activated_at: '2025-01-20T10:00:00Z',
    details: {
      brand: 'Toyota',
      model: 'Camry',
      year: 2020,
      mileage: 45000,
      transmission: 'automatic',
      fuel_type: 'hybrid',
      color: 'white',
      condition: 'excellent',
    },
    seller: {
      id: 'seller-1',
      name: 'Азамат PRO',
      avatar_url: 'https://i.pravatar.cc/150?img=12',
      is_verified: true,
    },
    business_id: 'business-1',
  },
  {
    id: '2',
    title: 'Harley-Davidson Fat Boy 2023',
    price: 3800000,
    currency: 'KGS',
    category: 'car', // Используем 'car' так как 'vehicle' не поддерживается
    seller_id: 'seller-2',
    video_id: 'video-2',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1558981403-c5f9898453d1?w=800&q=80',
    city: 'Ош',
    status: 'active',
    created_at: '2025-01-19T15:30:00Z',
    updated_at: '2025-01-19T15:30:00Z',
    views: 892,
    likes: 156,
    saves: 45,
    shares: 23,
    messages_count: 8,
    comments_count: 28,
    views_count: 892,
    likes_count: 156,
    ai_score: 97,
    details: {
      brand: 'Harley-Davidson',
      model: 'Fat Boy',
      year: 2023,
      mileage: 8500,
      transmission: 'manual',
      fuel_type: 'gasoline',
      color: 'black',
      condition: 'excellent',
    },
    seller: {
      id: 'seller-2',
      name: 'Байкер Эркин',
      avatar_url: 'https://i.pravatar.cc/150?img=15',
      is_verified: true,
    },
  },
  {
    id: '3',
    title: 'КамАЗ 6520 2022',
    price: 12500000,
    currency: 'KGS',
    category: 'car',
    seller_id: 'seller-3',
    video_id: 'video-3',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',
    city: 'Бишкек',
    status: 'active',
    created_at: '2025-01-18T09:15:00Z',
    updated_at: '2025-01-18T09:15:00Z',
    views: 567,
    likes: 78,
    saves: 12,
    shares: 5,
    messages_count: 3,
    comments_count: 9,
    views_count: 567,
    likes_count: 78,
    ai_score: 91,
    details: {
      brand: 'КамАЗ',
      model: '6520',
      year: 2022,
      mileage: 89000,
      transmission: 'manual',
      fuel_type: 'diesel',
      condition: 'good',
    },
    seller: {
      id: 'seller-3',
      name: 'Транспортная компания',
      avatar_url: 'https://i.pravatar.cc/150?img=8',
      is_verified: true,
    },
    business_id: 'business-3',
  },
  {
    id: '4',
    title: 'Ахалтекинский жеребец "Алтын"',
    price: 2500000,
    currency: 'KGS',
    category: 'horse',
    seller_id: 'seller-4',
    video_id: 'video-4',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1553284965-83fd8e9fa15a?w=800&q=80',
    city: 'Талас',
    status: 'active',
    created_at: '2025-01-17T14:20:00Z',
    updated_at: '2025-01-17T14:20:00Z',
    views: 456,
    likes: 134,
    saves: 67,
    shares: 34,
    messages_count: 12,
    comments_count: 45,
    views_count: 456,
    likes_count: 134,
    ai_score: 98,
    details: {
      breed: 'Ахалтекинская',
      age: 6,
      gender: 'stallion',
      color: 'golden',
      height: 168,
      temperament: 'spirited',
      training: 'advanced',
      purpose: 'sport',
      pedigree: true,
      health_certificate: true,
    },
    seller: {
      id: 'seller-4',
      name: 'Конезавод "Алтын Асаба"',
      avatar_url: 'https://i.pravatar.cc/150?img=21',
      is_verified: true,
    },
    business_id: 'business-4',
  },
  {
    id: '5',
    title: '3-комн. элитка в центре',
    price: 12500000,
    currency: 'KGS',
    category: 'real_estate',
    seller_id: 'seller-5',
    video_id: 'video-5',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    city: 'Бишкек',
    status: 'active',
    created_at: '2025-01-16T11:45:00Z',
    updated_at: '2025-01-16T11:45:00Z',
    views: 892,
    likes: 178,
    saves: 89,
    shares: 45,
    messages_count: 23,
    comments_count: 67,
    views_count: 892,
    likes_count: 178,
    ai_score: 96,
    details: {
      property_type: 'apartment',
      area: 98,
      area_unit: 'm2',
      rooms: 3,
      bedrooms: 3,
      bathrooms: 2,
      floor: 12,
      total_floors: 16,
      year_built: 2020,
      condition: 'excellent',
      parking: true,
      amenities: ['elevator', 'security', 'gym', 'parking'],
    },
    seller: {
      id: 'seller-5',
      name: 'Агентство "Дом Мечты"',
      avatar_url: 'https://i.pravatar.cc/150?img=25',
      is_verified: true,
    },
    business_id: 'business-5',
  },
];

export const MOCK_SEARCH_RESULT = {
  data: MOCK_LISTINGS,
  total: MOCK_LISTINGS.length,
  hasMore: false,
};
