// services/mockData.ts
// 🧪 Тестовые данные для разработки

export const MOCK_LISTINGS = [
  {
    id: '1',
    title: 'Toyota Camry 2020',
    price: 2500000,
    category: 'auto',
    city: 'Бишкек',
    status: 'active',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail_url: 'https://via.placeholder.com/400x300/FF6B35/FFFFFF?text=Toyota+Camry',
    ai_score: 85,
    views: 234,
    likes: 45,
    seller_id: 'test-user-1',
    brand: 'Toyota',
    model: 'Camry',
    year: 2020,
    mileage: 45000,
    transmission: 'automatic',
    fuel_type: 'gasoline',
    color: 'white',
    description: 'Отличное состояние, один владелец, полная комплектация',
    created_at: '2025-01-20T10:00:00Z',
    seller: {
      id: 'test-user-1',
      name: 'Азамат Продавец',
      avatar_url: 'https://i.pravatar.cc/150?img=1',
      is_verified: true
    }
  },
  {
    id: '2',
    title: 'BMW X5 2019',
    price: 4500000,
    category: 'auto',
    city: 'Ош',
    status: 'active',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail_url: 'https://via.placeholder.com/400x300/0066CC/FFFFFF?text=BMW+X5',
    ai_score: 92,
    views: 567,
    likes: 89,
    seller_id: 'test-user-2',
    brand: 'BMW',
    model: 'X5',
    year: 2019,
    mileage: 32000,
    transmission: 'automatic',
    fuel_type: 'gasoline',
    color: 'black',
    description: 'Премиум комплектация, сервисная история, без ДТП',
    created_at: '2025-01-19T15:30:00Z',
    seller: {
      id: 'test-user-2',
      name: 'Эльмира Автодилер',
      avatar_url: 'https://i.pravatar.cc/150?img=2',
      is_verified: true
    }
  },
  {
    id: '3',
    title: 'Honda Civic 2021',
    price: 1800000,
    category: 'auto',
    city: 'Бишкек',
    status: 'active',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_url: 'https://via.placeholder.com/400x300/FF0000/FFFFFF?text=Honda+Civic',
    ai_score: 78,
    views: 123,
    likes: 23,
    seller_id: 'test-user-3',
    brand: 'Honda',
    model: 'Civic',
    year: 2021,
    mileage: 28000,
    transmission: 'manual',
    fuel_type: 'gasoline',
    color: 'red',
    description: 'Экономичный, надежный, идеально для города',
    created_at: '2025-01-18T09:15:00Z',
    seller: {
      id: 'test-user-3',
      name: 'Нурбек Молодой',
      avatar_url: 'https://i.pravatar.cc/150?img=3',
      is_verified: false
    }
  },
  {
    id: '4',
    title: 'Арабский скакун',
    price: 1200000,
    category: 'horse',
    city: 'Талас',
    status: 'active',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnail_url: 'https://via.placeholder.com/400x300/8B4513/FFFFFF?text=Арабский+скакун',
    ai_score: 94,
    views: 89,
    likes: 34,
    seller_id: 'test-user-4',
    breed: 'Арабская',
    age: 5,
    gender: 'male',
    color: 'bay',
    description: 'Чистокровный арабский скакун, отличная родословная',
    created_at: '2025-01-17T14:20:00Z',
    seller: {
      id: 'test-user-4',
      name: 'Айбек Коневладелец',
      avatar_url: 'https://i.pravatar.cc/150?img=4',
      is_verified: true
    }
  },
  {
    id: '5',
    title: 'Квартира 3-комн. в центре',
    price: 8500000,
    category: 'real_estate',
    city: 'Бишкек',
    status: 'active',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnail_url: 'https://via.placeholder.com/400x300/228B22/FFFFFF?text=Квартира+3к',
    ai_score: 88,
    views: 445,
    likes: 67,
    seller_id: 'test-user-5',
    property_type: 'apartment',
    rooms: 3,
    area: 85,
    floor: 5,
    total_floors: 9,
    description: 'Современная планировка, евроремонт, вид на горы',
    created_at: '2025-01-16T11:45:00Z',
    seller: {
      id: 'test-user-5',
      name: 'Айгуль Риелтор',
      avatar_url: 'https://i.pravatar.cc/150?img=5',
      is_verified: true
    }
  },
  {
    id: '6',
    title: 'Ахалтекинская лошадь',
    price: 1200000,
    category: 'horse',
    city: 'Ош',
    status: 'active',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_url: 'https://via.placeholder.com/400x300/D2691E/FFFFFF?text=Ахалтекинская',
    ai_score: 96,
    views: 156,
    likes: 42,
    seller_id: 'test-user-6',
    breed: 'Ахалтекинская',
    age: 7,
    gender: 'female',
    color: 'palomino',
    height: 165,
    temperament: 'calm',
    description: 'Элитная ахалтекинская кобыла, идеальна для выездки',
    created_at: '2025-01-15T09:30:00Z',
    seller: {
      id: 'test-user-6',
      name: 'Гульнара Коневладелец',
      avatar_url: 'https://i.pravatar.cc/150?img=6',
      is_verified: true
    }
  },
  {
    id: '7',
    title: 'Орловский рысак',
    price: 800000,
    category: 'horse',
    city: 'Каракол',
    status: 'active',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail_url: 'https://via.placeholder.com/400x300/2F4F4F/FFFFFF?text=Орловский+рысак',
    ai_score: 89,
    views: 98,
    likes: 28,
    seller_id: 'test-user-7',
    breed: 'Орловский рысак',
    age: 4,
    gender: 'male',
    color: 'gray',
    height: 170,
    temperament: 'energetic',
    description: 'Молодой орловский рысак, отличные беговые качества',
    created_at: '2025-01-14T16:15:00Z',
    seller: {
      id: 'test-user-7',
      name: 'Эрлан Коневладелец',
      avatar_url: 'https://i.pravatar.cc/150?img=7',
      is_verified: false
    }
  },
  {
    id: '8',
    title: 'Дом с участком',
    price: 12000000,
    category: 'real_estate',
    city: 'Джалал-Абад',
    status: 'active',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnail_url: 'https://via.placeholder.com/400x300/8B4513/FFFFFF?text=Дом+с+участком',
    ai_score: 91,
    views: 234,
    likes: 45,
    seller_id: 'test-user-8',
    property_type: 'house',
    rooms: 4,
    area: 120,
    floor: 1,
    total_floors: 2,
    building_type: 'brick',
    description: 'Частный дом с большим участком, гараж, сад',
    created_at: '2025-01-13T12:00:00Z',
    seller: {
      id: 'test-user-8',
      name: 'Бакыт Риелтор',
      avatar_url: 'https://i.pravatar.cc/150?img=8',
      is_verified: true
    }
  },
  {
    id: '9',
    title: 'Офисное помещение',
    price: 6500000,
    category: 'real_estate',
    city: 'Бишкек',
    status: 'active',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnail_url: 'https://via.placeholder.com/400x300/4682B4/FFFFFF?text=Офис+100м²',
    ai_score: 87,
    views: 178,
    likes: 32,
    seller_id: 'test-user-9',
    property_type: 'office',
    rooms: 2,
    area: 100,
    floor: 3,
    total_floors: 5,
    building_type: 'concrete',
    description: 'Современное офисное помещение в бизнес-центре',
    created_at: '2025-01-12T14:45:00Z',
    seller: {
      id: 'test-user-9',
      name: 'Айнура Риелтор',
      avatar_url: 'https://i.pravatar.cc/150?img=9',
      is_verified: true
    }
  }
];

export const MOCK_SEARCH_RESULT = {
  data: MOCK_LISTINGS,
  total: MOCK_LISTINGS.length,
  hasMore: false
};
