"use strict";
// Типы для системы бизнес-аккаунтов
Object.defineProperty(exports, "__esModule", { value: true });
exports.FREE_LIMITS = exports.TIER_CONFIGS = void 0;
// Константы тарифов
exports.TIER_CONFIGS = {
    free: {
        tier: 'free',
        name: 'Базовый',
        price: 0,
        maxListings: 2,
        maxTeamMembers: 1,
        hasAnalytics: false,
        hasAdvancedAnalytics: false,
        hasLogo: false,
        hasDescription: false,
        hasPriorityBoost: 0,
        hasBoostDiscount: 0,
        hasAutoRenew: false,
        hasTemplates: false,
        hasBulkUpload: false,
        hasVerification: false,
        hasBrandedPage: false,
        hasQRCode: false,
        hasBanner: false,
        features: [
            'До 2 транспорта',
            'До 2 лошадей',
            'До 1 недвижимости',
        ],
    },
    lite: {
        tier: 'lite',
        name: 'Лайт',
        price: 300,
        maxListings: 10,
        maxTeamMembers: 1,
        hasAnalytics: true,
        hasAdvancedAnalytics: false,
        hasLogo: true,
        hasDescription: false,
        hasPriorityBoost: 0,
        hasBoostDiscount: 20,
        hasAutoRenew: false,
        hasTemplates: false,
        hasBulkUpload: false,
        hasVerification: false,
        hasBrandedPage: false,
        hasQRCode: false,
        hasBanner: false,
        features: [
            'До 10 активных объявлений',
            'Логотип компании',
            '1 менеджер',
            'Базовая аналитика',
            'Скидка на Boost -20%',
        ],
    },
    business: {
        tier: 'business',
        name: 'Бизнес',
        price: 500,
        maxListings: 30,
        maxTeamMembers: 3,
        hasAnalytics: true,
        hasAdvancedAnalytics: true,
        hasLogo: true,
        hasDescription: true,
        hasPriorityBoost: 20,
        hasBoostDiscount: 30,
        hasAutoRenew: true,
        hasTemplates: true,
        hasBulkUpload: false,
        hasVerification: false,
        hasBrandedPage: false,
        hasQRCode: false,
        hasBanner: false,
        features: [
            'До 30 активных объявлений',
            'Логотип + описание компании',
            'До 3 менеджеров',
            'Расширенная аналитика',
            'Приоритет в ленте +20%',
            'Автопродление',
            'Шаблоны объявлений',
            'Скидка на Boost -30%',
        ],
    },
    pro: {
        tier: 'pro',
        name: 'Профи',
        price: 1500,
        maxListings: 'unlimited',
        maxTeamMembers: 'unlimited',
        hasAnalytics: true,
        hasAdvancedAnalytics: true,
        hasLogo: true,
        hasDescription: true,
        hasPriorityBoost: 50,
        hasBoostDiscount: 50,
        hasAutoRenew: true,
        hasTemplates: true,
        hasBulkUpload: true,
        hasVerification: true,
        hasBrandedPage: true,
        hasQRCode: true,
        hasBanner: true,
        features: [
            'Безлимит объявлений',
            'Безлимит менеджеров',
            'Приоритет в ленте +50%',
            'Баннер в ленте (каждое 10-е видео)',
            'Bulk загрузка',
            'Верификация PRO (синий значок)',
            'Брендированная страница',
            'QR код + виджет сайта',
            'Скидка на Boost -50%',
        ],
    },
};
// Лимиты для FREE аккаунтов по категориям
exports.FREE_LIMITS = {
    car: 2,
    horse: 2,
    realty: 1,
};
