-- ============================================
-- Fix users.id DEFAULT constraint
-- Ensures id column has gen_random_uuid() default
-- ============================================

-- Force set default value for id column (works even if table already exists)
ALTER TABLE public.users 
ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- Also create a helper function to create users (bypasses RLS issues)
CREATE OR REPLACE FUNCTION public.create_user_profile(
  p_phone VARCHAR(20),
  p_name VARCHAR(255) DEFAULT 'Пользователь',
  p_is_verified BOOLEAN DEFAULT FALSE
)
RETURNS TABLE(
  id UUID,
  phone VARCHAR(20),
  name VARCHAR(255),
  is_verified BOOLEAN,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
) 
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Insert user with explicit id (generated by gen_random_uuid())
  -- ON CONFLICT updates existing user and returns it
  -- Return the user data directly
  RETURN QUERY
  INSERT INTO public.users (id, phone, name, is_verified, created_at, updated_at)
  VALUES (gen_random_uuid(), p_phone, p_name, p_is_verified, NOW(), NOW())
  ON CONFLICT (phone) DO UPDATE
  SET updated_at = NOW()
  RETURNING 
    users.id,
    users.phone,
    users.name,
    users.is_verified,
    users.created_at,
    users.updated_at;
END;
$$;

